{{- if .Values.scheduler.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "starcitizen-api.fullname" . }}-scheduler
  labels:
    {{- include "starcitizen-api.componentLabels" (dict "context" . "component" "scheduler") | nindent 4 }}
  {{- with (include "starcitizen-api.commonAnnotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "starcitizen-api.componentSelectorLabels" (dict "context" . "component" "scheduler") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "starcitizen-api.componentLabels" (dict "context" . "component" "scheduler") | nindent 8 }}
        {{- with .Values.scheduler.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        {{- include "starcitizen-api.checksumAnnotations" . | nindent 8 }}
        {{- with .Values.scheduler.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "starcitizen-api.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "starcitizen-api.initContainers" . | nindent 8 }}
      containers:
        - name: scheduler
          image: {{ include "starcitizen-api.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.scheduler.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CONTAINER_ROLE
              value: scheduler
            {{- include "starcitizen-api.secretEnv" . | nindent 12 }}
          envFrom:
            {{- include "starcitizen-api.envFrom" . | nindent 12 }}
          {{- with .Values.scheduler.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "starcitizen-api.volumeMounts" . | nindent 12 }}
      volumes:
        {{- include "starcitizen-api.volumes" . | nindent 8 }}
      {{- with .Values.scheduler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.scheduler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
