apiVersion: v1
kind: Service
metadata:
  name: {{ include "starcitizen-api.fullname" . }}
  labels:
    {{- include "starcitizen-api.componentLabels" (dict "context" . "component" "api") | nindent 4 }}
  {{- with .Values.api.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "starcitizen-api.componentSelectorLabels" (dict "context" . "component" "api") | nindent 4 }}
